---
Default Meta Description: manticore description
Default Meta Tags: manticore, default, tags
Telephone Number: 01482 226 754
Name: CTS Shopfitting Ltd
Fax Number: 01482 585 096
Email: sales@ctsshopfitting.co.uk
Address: 2 Sullivan Business Park, Scarborough Street, Hull, HU3 4TG
